version: "3.9"
services:
  dns-tls-proxy:
    build: .
    ports:
      - "5360:5360"
      - "5365:5365/udp"
    environment:
      PORT_TCP: "5360"
      PORT_UDP: "5365"
      DNS_SERVER_HOST: "1.1.1.1"
      DNS_SERVER_HOST_NAME: "cloudflare-dns.com"
      DNS_SERVER_PORT_TLS: "853"
      UDP: "true"
      TCP: "true"
